version: 0.2

phases:
  build:
    commands:
      - echo "Preparing to deploy frontend to S3..."
  post_build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync . s3://<YOUR_S3_BUCKET> --delete --exclude "buildspec.yml" --exclude "cf.yaml" --exclude "lib/*"
