AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Amazon OpenSearch Service domain (photoscf) with t3.small.search instance type"

Resources:
  PhotosCFDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      DomainName: "photoscf"
      EngineVersion: "OpenSearch_2.5"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeType: "gp3"
        VolumeSize: 10
      SnapshotOptions:
        AutomatedSnapshotStartHour: 0
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: 'arn:aws:iam::584371126097:user/opensearch-user'
            Action: "es:*"
            Resource: !Sub 'arn:aws:es:us-east-1:584371126097:domain/photoscf/*'

  S3Bucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: "hw2bucket1weiyaoli"
      WebsiteConfiguration:
        IndexDocument: index.html

  S3Bucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: "hw2bucket2weiyaoli"


  indexPhoto:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: arn:aws:iam::584371126097:role/service-role/index-photos-role-rf08ykeb
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: bucketforlambdaweiyaoli
        S3Key: ezyzip-2.zip

  searchPhoto:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: python3.9
      Role: arn:aws:iam::584371126097:role/service-role/search-photos-role-t5agtqe5
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: bucketforlambdaweiyaoli
        S3Key: ezyzip.zip

  photoAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      CloneFrom: '8vnqwtfglj'
      Name: 'photoSearch'
