version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --target ./package requests-aws4auth opensearch-py boto3
  post_build:
    commands:
      - echo "Zipping deployment packages..."
      - cp Lambda/LF1-index.py lambda_function.py
      - cd package
      - zip -r9 ../deployment_package_lf1.zip .
      - cd ..
      - zip -g deployment_package_lf1.zip lambda_function.py
      - cp Lambda/LF2-search.py lambda_function.py
      - cd package
      - zip -r9 ../deployment_package_lf2.zip .
      - cd ..
      - zip -g deployment_package_lf2.zip lambda_function.py
      - echo "Updating Lambda functions..."
      - aws lambda update-function-code --function-name cfcloudformation-indexPhoto-Jt59Lnz8oJjI --zip-file fileb://deployment_package_lf1.zip
      - aws lambda update-function-code --function-name cfcloudformation-searchPhoto-Tjdr0ySiXHD5 --zip-file fileb://deployment_package_lf2.zip
