version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r Lambda/requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment packages..."
      - cd lib
      - zip -r9 ../deployment_package_lf1.zip .
      - zip -r9 ../deployment_package_lf2.zip .
      - cd ..
      - zip -g deployment_package_lf1.zip Lambda/LF1-index.py
      - zip -g deployment_package_lf2.zip Lambda/LF2-search.py
  post_build:
    commands:
      - echo "Updating Lambda Function 1..."
      - aws lambda update-function-code --function-name cfcloudformation-indexPhoto-Jt59Lnz8oJjI --zip-file fileb://deployment_package_lf1.zip
      - echo "Updating Lambda Function 2..."
      - aws lambda update-function-code --function-name cfcloudformation-searchPhoto-Tjdr0ySiXHD5 --zip-file fileb://deployment_package_lf2.zip
      - echo "DONE!!"